[project]
name = "neotomadoi"
version = "0.1.0"
description = "Minting process for the Neotoma Paleoecology Database's DOIs using DataCite."
readme = "README.md"
authors = [
    { name = "Simon Goring", email = "goring@wisc.edu" }
]
requires-python = ">=3.12"
dependencies = [
    "argparse>=1.4.0",
    "datacite>=1.2.0",
    "jsonschema>=4.23.0",
    "psycopg2>=2.9.10",
    "pyalex>=0.18",
    "python-dotenv>=1.1.0",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "setuptools>=79.0.0",
    "shapely>=2.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
